### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by zacwebb** [nuxt-hub/core#116]
I've had a read of #46, but I'm wondering if there's plans for a built-in approach to running migrations?

As much as running the dev server in remote mode works, I'd be much more confident in shipping if there was a proper way to do it. Currently most of my production services run on and I'm quite fond of [their pre-deployment command](https://docs.render.com/deploys#pre-deploy-command) to run migrations – maybe something similar could work for NuxtHub?

Currently I've got one project deploying with nuxthub to CF using a Github action to handle the deploy/migration process:

```yaml
on:
  push:
    branches:
      - master

name: Deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build --preset=cloudflare_pages

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  migrate:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Configure wrangler.toml
        run: cp wrangler.prod.toml wrangler.toml

      - name: Run migration with wrangler
        run: pnpm i && pnpm wrangler d1 migrations apply [db_name] --remote
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}    
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}    

  deploy:
    name: Deploy Built Code
    runs-on: ubuntu-latest
    needs: [migrate]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - uses: actions/download-artifact@v4
        with:
          name: dist
  
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=[project name]
``` 

But this requires me having a separate wrangler.toml with the production database details in it to run the migrations using wrangler:

```yaml
d1_databases = [
  { binding = "DB", database_name = "[database_name]", database_id = "[cf_database_uuid]", migrations_dir = "server/database/migrations" },
]
```

Any ideas on how to improve this setup to avoid having the separate wrangler file, and is the idea of something like the pre-deploy command something that would be considered for NuxtHub?
