### ISSUE TITLE
[action]: workflow file generated by nuxthub-admin[bot] contains an error

### ISSUE THREAD

**Issue by ZTL-UwU** [nuxt-hub/core#418]
**Describe the bug**

In the `.github/workflows/nuxthub.yml` generated by the action bot:

```yml
steps:
  - uses: actions/checkout@v4
  - name: Install pnpm
    uses: pnpm/action-setup@v4
      with:
        version: 9
```

The `with:` has the wrong indent which causes a syntax error.

![image](https://github.com/user-attachments/assets/4905b82f-9d47-4eb8-be0f-28874773f794)

**Steps to reproduce**

The original commit: https://github.com/ZTL-UwU/cn-lorem-ipsum/commit/873de30ef1960f7e384768e3b740f7b9f9fc66af

1. Create a new project on nuxt hub admin with an existing github project
2. Go to action tab on the project
3. See error

**Expected behavior**

`.github/workflows/nuxthub.yml` is correctly generated.
