### ISSUE TITLE
NuxtUI Pro will not deploy to NuxtHub

### ISSUE THREAD

**Issue by ratracegrad** [nuxt-hub/core#430]
I have deployed my app multiple times to NuxtHub. I have added NuxtUI Pro. It will not deploy because of my NuxtUIPro is not being read. 

My NuxtUI Pro license is validated.

I have updated my nuthub.yml file to be:

```
name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: three-quartiles-4h4d
```

In my NuxtHub admin in Environments I have my `NUXT_UI_PRO_LICENSE` and it is deplyed as you can see in this screenshot:

![Image](https://github.com/user-attachments/assets/c453ec56-6db5-4a73-a3f7-673f041359d4)

The `Deploy to NuxtHub` task fails with:

```
[info] Running with compatibility version `4`
[info] [nuxi] Building for Nitro preset: `cloudflare-pages`
Error:  Missing `NUXT_UI_PRO_LICENSE` license key.
Purchase Nuxt UI Pro at `[https://ui.nuxt.com/pro/pricing`](https://ui.nuxt.com/pro/pricing%60) to build your app in production.
 

Error:  Missing `NUXT_UI_PRO_LICENSE` license key.
Purchase Nuxt UI Pro at `[https://ui.nuxt.com/pro/pricing`](https://ui.nuxt.com/pro/pricing%60) to build your app in production.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by RihanArfan** [comment]
If you're on GitHub's free tier, we don't sync environment variables or secrets since environments are only available on paid plans. You can add a repository secret called `NUXT_UI_PRO_LICENSE` via Repository Settings -> Secrets and variables -> Actions (and also on Dependabot too if you use that)

**Comment by DavidSabine** [comment]
I suggest this issue be re-opened.

Reasons:

1) The solution suggested by @RihanArfan is not reliable. I did as suggested but still could not deploy successfully. Either a detail is missing or the instruction is not appropriate in my case.

2) This is terrible Customer Experience: your customer works locally with Nuxt UI Pro, makes a personal commitment to integrate it into their Nuxt app, then PAYS MONEY for the key, then tries to deploy to hub.nuxt expecting that the ecosystem is seamless (I mean, why not deploy on Vercel or Netlify except that this is a host specializing in NUXT apps!), then crashes into this obscure limitation.

3) I was able to successfully deploy after adding finding this strange documentation: https://ui.nuxt.com/pro/getting-started/installation#uiprolicense and I think this CANNOT be the official recommendation?! My repo is currently private, but this is very bad practice to put secrets into plain text config files in the repo.

I would be interested to learn whether @ratracegrad was able to overcome this obstacle? It looks like @RihanArfan quickly closed the issue without learning whether the advice was actionable.

**Comment by RihanArfan** [comment]
Hi @DavidSabine, thank you for raising these points. I understand the current requirement requiring updating your GitHub Actions workflow file to reference secrets isn't ideal at all and we're investigating ways to improve this.

We have a guide for using GitHub secrets during build time on our docs - it requires making a modification to your workflow file to utilise the GitHub secret. https://hub.nuxt.com/docs/getting-started/deploy#environment-variables-secrets. If your repo is on a free GitHub account/org, you'll need to follow the steps in my previous reply to set the secret too. Otherwise, setting/updating the secret from NuxtHub Admin will set the secret on GitHub.

It should definitely be possible to deploy Nuxt UI Pro without hardcoding the secret inside your code. In order to investigate your deployment problem, please could you share your GitHub Actions workflow file and I'll take a look.

**Comment by DavidSabine** [comment]
Hello @RihanArfan,

My repo is on a free GitHub account, yes.

I read the doc at /docs/getting-started/deploy#env...::

I then:

1. created the secret at github
2. added the env variable to nuxthub (and ran nuxthub deploy --no-build to ensure the variable was replicated at cloudflare)
3. and modified my nuxthub.yml as follows:

![Image](https://github.com/user-attachments/assets/36520a2b-bffe-45ae-b1b5-4969a19ab2b8)

![Image](https://github.com/user-attachments/assets/f99a182b-9a6f-45df-900f-df23603b7b5a)

![Image](https://github.com/user-attachments/assets/7a65d197-bbf8-4159-8c7e-e5bdce1bc8ba)

You can see VSCode doesn't like the syntax in the yml file - but more importantly, it fails to deploy whether I use `npx nuxthub deploy` or commit to GitHub (to trigger the action).

**Comment by RihanArfan** [comment]
Hmm this is certainly very strange. Your workflow file and secret name appear to be correct. Just to confirm, is the secret under Actions? Also, could you double check the license key is correct?

You can test the license key by setting `NUXT_UI_PRO_LICENSE=` inside your `.env` file locally, then running `npx nuxthub deploy` or `npm run build`. I suspect local builds are failing due to the lack of license key set when trying to build.

I've tested deploying a Nuxt UI Pro template from scratch successfully.
1. Created template from https://github.com/nuxt-ui-pro/starter to an org without a subscription
2. `pnpx nuxi module add hub` and pushed
3. Imported to NuxtHub
4. Added the secret to GitHub
5. Edited the workflow to use the secret

![Image](https://github.com/user-attachments/assets/f9633d7d-7966-4701-8fc4-f60312709567)

![Image](https://github.com/user-attachments/assets/66b3ddd8-6564-47ab-a88b-91938b4d7b2a)

<details><summary>.github/workflows/nuxthub.yml</summary>
<p>

```yaml
name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/v3' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: nuxt-ui-pro-nux-nvtb
``` 

</p>
</details>
